package com.example.homework.model;


import lombok.Data;

@Data
public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.NUMBER
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.SCHOOL
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.username
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ADDRESS
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.WECHAT
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.JOB
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PASSWORD
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.NUMBER
     *
     * @return the value of ACCOUNT.NUMBER
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     * @param number
     */
    public String getNumber(String number) {
        return this.number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.NUMBER
     *
     * @param number the value for ACCOUNT.NUMBER
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.SCHOOL
     *
     * @return the value of ACCOUNT.SCHOOL
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     * @param school
     */
    public String getSchool(String school) {
        return this.school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.SCHOOL
     *
     * @param school the value for ACCOUNT.SCHOOL
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.username
     *
     * @return the value of ACCOUNT.username
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     * @param username
     */
    public String getUsername(String username) {
        return this.username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.username
     *
     * @param username the value for ACCOUNT.username
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ADDRESS
     *
     * @return the value of ACCOUNT.ADDRESS
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ADDRESS
     *
     * @param address the value for ACCOUNT.ADDRESS
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.WECHAT
     *
     * @return the value of ACCOUNT.WECHAT
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.WECHAT
     *
     * @param wechat the value for ACCOUNT.WECHAT
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.JOB
     *
     * @return the value of ACCOUNT.JOB
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.JOB
     *
     * @param job the value for ACCOUNT.JOB
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PASSWORD
     *
     * @return the value of ACCOUNT.PASSWORD
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PASSWORD
     *
     * @param password the value for ACCOUNT.PASSWORD
     *
     * @mbg.generated Tue Nov 12 22:31:39 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}